---
title: "Moscas Manova"
author:
      - "Matheus Gomes"
      - "Daniela Moraes"
      - "Marcos Ferreira"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

```

#Moscas

##Pacotes
```{r, message = F, warning = F}
source("funcoes.R")
pacotes <- c("ggplot2",
             "magrittr",
             "gridExtra",
             "xtable",
             "dplyr",
             "purrr",
             "tidyr",
             "car",
             "broom")

ipak(pacotes)
options(xtable.comment = FALSE,OutDec = ",")
```

##Lendo Os Dados

```{r}

dados <- read.table("Dados/Moscas.txt")

nomes_COl <- c("Especie" = "Especie",
              "CompAsa" =  "Comprimento da asa",
              "LargAsa" = "Largura da asa",
              "Comp3Palpo" = "Comprimento do terceiro\npalpo",
              "Larg3Palpo" =  "Largura do terceiro\npalpo", 
              "Comp4Palpo" = "Comprimento do quarto\npalpo",
              "Comp12Antena" = 
           "Comprimento do 12º\nsegmento da antena",
            "Comp13Antena" =  "Comprimento do 13º\nsegmento da antena")



colnames(dados) <- c("Especie","CompAsa","LargAsa","Comp3Palpo",          "Larg3Palpo","Comp4Palpo","Comp12Antena","Comp13Antena")

Especie_chr <- function(x){
  if (x == 0)
    y <- "torrens"
  else
    y <- "carteri"
}
dados %<>% mutate( Especie_fct = 
                    factor(map_chr(Especie,Especie_chr)))


```


#Analise Descritiva

##Preparação

```{r}
mx <- dados[,2:8] %>% as.matrix()
nvar <- 7
n <- 70
```


##Medidas Descritivas

```{r results = "asis"}

descritivas <- 
dados %>% select_if(.predicate = is.integer) %>% 
  gather(Coluna,valores,-Especie) %>% 
  group_by(Coluna,Especie) %>% 
  summarise_if(.predicate = function(x) is.numeric(x),
                  .funs = c(Média = "mean",
                     DP = "sd",
                     Var. = "var",
                     Mínimo = "min",
                     CV =  "cv",
                     Mediana = "median",
                     Máximo = "max")) %>% 
  mutate_if(.predicate = is.numeric,funs(round(.,3))) %>% 
  mutate(Espécie =  factor(map_chr(Especie,Especie_chr))) %>% 
  select(-Especie)
names(descritivas )[names(descritivas ) == 'CV'] <- 'CV(%)'
descritivas <- descritivas[,c(1,9,2:8)]
descritivas_2 <- nest(descritivas)

for(i in 1:7){
  print.xtable(xtable(descritivas_2$data[[i]], 
         caption = nomes_COl[descritivas_2$Coluna[i]]), include.rownames = F)
}

```



\newpage

##Boxplots

```{r}
##criando funcao para facilitar a criação dos boxplots
boxplots_moscas <- function(coluna){
 qplot(dados$Especie_fct,coluna,geom = "boxplot") + labs(x = "Espécie") + theme_bw()
}

graficos <- apply(dados[,2:8],2,boxplots_moscas)

for(i in 1:7)
 graficos[[i]] <-  graficos[[i]] + labs(y = nomes_COl[i + 1])
  
##print os boxplots
grid.arrange(graficos[[1]], graficos[[2]], 
             graficos[[3]], graficos[[4]])

grid.arrange(graficos[[5]], graficos[[6]], 
             graficos[[7]], 
            layout_matrix = rbind(c(1,1),c(2,3)))


```

##Histograma

```{r}

##criando funcao para facilitar a criação dos boxplots
hist_moscas <- function(coluna){
 qplot(coluna,geom = "histogram",col = I("black"),fill = I("white"),
       binwidth = 1) + theme_bw() 
}

graficos <- apply(dados[,2:8],2,hist_moscas)

for (i in 1:7)
 graficos[[i]] <-  graficos[[i]] + labs(x = nomes_COl[i + 1],y = NULL)
  
##print os boxplots
grid.arrange(graficos[[1]], graficos[[2]], 
             graficos[[3]], graficos[[4]])

grid.arrange(graficos[[5]], graficos[[6]], 
             graficos[[7]], 
            layout_matrix = rbind(c(1,1),c(2,3)))
```

##Diagrama Dispersao


```{r}

cols <- character(nrow(dados))
cols[] <- "black"

cols[dados$Especie_fct == "carteri"] <- "red"
cols[dados$Especie_fct == "torrens"] <- "blue"
pairs(dados[,2:8],col=cols,upper.panel = NULL)
par(xpd = T)
legend("topright", legend = c(levels(dados$Especie_fct)), 
       fill = c("blue","red"))

```



##Distancia de Mahalanobis


```{r}
par(mfrow = c(1,2))

# Envelopes para a forma quadratica
#
mu <- apply(dados[dados$Especie == 0, 2:8], 2, mean)
s2 <- cov(dados[dados$Especie == 0,2:8])
vQ <- n*mahalanobis(mx,center = mu,cov = s2)
qqPlot(vQ, dist = "chisq", df = nvar, col.lines = 1, grid = "FALSE", xlab = "quantil da distribuição qui-quadrado", ylab = "quantil da forma quadratica", cex = 1.2, id.cex = 1.2, main = "Torrens")

##

mu <- apply(dados[dados$Especie == 1, 2:8],2,mean)
s2 <- cov(dados[dados$Especie == 1,2:8])
vQ <- n*mahalanobis(mx,center = mu,cov = s2)

qqPlot(vQ, dist = "chisq", df = nvar, col.lines = 1, grid = "FALSE", xlab = "quantil da distribuição qui-quadrado", ylab = "quantil da forma quadratica", cex = 1.2, id.cex = 1.2, main = "Carteri")

```

#Analise Inferencial


```{r results = "asis"}
m.ajuste <- manova(as.matrix(dados[,2:8]) ~ dados[,9])
Wilks <- summary.manova(m.ajuste,test="Wilks")$stats
Pillai <- summary.manova(m.ajuste,test="Pillai")$stats
Hotelling <- summary.manova(m.ajuste, test = "Hotelling-Lawley")$stats
Roy <- summary.manova(m.ajuste,test = "Roy")$stats
manova_stats <- list("Wilks" = Wilks,
                     "Pillai" =  Pillai,
                     "Hotelling-Lawley" = Hotelling,
                     "Roy" = Roy )
tbl_manova <- data.frame("Estatística" = names(manova_stats),
                         "Valor" = map_dbl(manova_stats,3),
                        "Aproximação.pela.\n.distribuição.F" = map_dbl(manova_stats,5),
                        "p-valor" = "<0,01" )  %>%
   mutate_if(.predicate = is.numeric,funs(round(.,2))) %>%
  as.matrix

colnames(tbl_manova ) <- c("Estatística","Valor",
                    "Aproximação pela distribuição F",
                     "p-valor")
tbl_m <- xtable(tbl_manova,caption = "Resultados da MANOVA")
align( tbl_m) <- c( 'l', 'p{1.5in}', rep('c',3) )
print.xtable(tbl_m,include.rownames = F)

```

##Estimativas 

\newpage

```{r results = "asis"}

##ajustando modelo linear
Especie <- dados[,9]
fit.modelLM <- lm(as.matrix(dados[,2:8]) ~ Especie)
##tranformando o resultado em uma lista de data.frames
summ_dados <- summary(fit.modelLM)
Estimativas <- map(summ_dados,tidy)
##ajuste para imprimir os resultados
names(Estimativas) <- gsub("Response ","",names(Estimativas))
Estimativas <-  map(Estimativas, ~mutate_if(.,.predicate = is.numeric, funs(round(.,5))))

Super_Estimativas <- tibble(Variavel = names(Estimativas),data = Estimativas) %>% unnest() %>%
  mutate(term = parametro(14),Variavel = acertar_coluna(Variavel),
         p.value = ifelse(p.value<0.01,"<0.01",round(p.value,2)))
names(Super_Estimativas) <- c("Variável","Parâmetro","Estimativa",
                              "Erro Padrão","Estatística t",
                              "p-valor")
tab <- xtable(Super_Estimativas)
print(tab,sanitize.text.function = function(x) {x},include.rownames = F,hline.after = c(-1,0,seq(2,14,2)))
```


##graficos medias + intervalo de confiança

```{r}


Super_Estimativas <- tibble(Coluna = names(Estimativas),data = Estimativas) %>% unnest() %>%
  mutate(Espécie = ifelse(term == "(Intercept)","carteri","torrens"))

descritivas <- 
dados %>% select_if(.predicate = is.integer) %>% 
  gather(Coluna,valores,-Especie) %>% 
  group_by(Coluna,Especie) %>% 
  summarise_if(.predicate = function(x) is.numeric(x),
                  .funs = c(Média = "mean")) %>% 
  mutate_if(.predicate = is.numeric,funs(round(.,3))) %>% 
  mutate(Espécie =  factor(map_chr(Especie,Especie_chr))) %>% 
  select(-Especie)

 IC <- left_join(Super_Estimativas,descritivas) %>% 
  select(Coluna,Espécie,Média,std.error) %>% 
   mutate(conf.low = Média - 1.96*std.error, 
          conf.high = Média + 1.96*std.error)


plots_IC <- list()

for( i in 1:7){
plots_IC[[i]] <- IC %>% 
  filter(Coluna == unique(IC$Coluna)[i]) %>% 
  ggplot(aes(x= Espécie, y = Média)) + geom_point() +
  geom_errorbar(aes(ymin = conf.low,ymax = conf.high), size =  0.4,width = .3) + coord_flip() + theme_bw() + 
  labs(title =  nomes_COl[unique(IC$Coluna)[i]]) +
   theme(plot.title = element_text(lineheight=.8, 
                                        face="bold",hjust = 0.5)) 
}

grid.arrange(plots_IC[[1]], plots_IC[[2]], 
             plots_IC[[3]], plots_IC[[4]])

grid.arrange(plots_IC[[5]], plots_IC[[6]], 
             plots_IC[[7]], 
            layout_matrix = rbind(c(1,1),c(2,3)))
```

##CBU = M

```{r results = "asis"}
source("MANOVA_CAIO.R")
p <- 7 ##variaveis
G <- 2 ## grupos
m.Sigma.P <- Box.teste.Igual.MCov(dados[,2:8], as.matrix(dados[,1]+1) ,rbind(35,35),G)$Sigma.P
m.ajuste <- manova(as.matrix(dados[,2:8]) ~ as.factor(dados[,1]+1))
m.C1 <- cbind(0,1) #  Torrens X Carteri
m.U <- rbind(1,0,0,0,0,0,0)
m.M <- 0

for(i in 1:7) {

  if( i == 1)
     CBU <- TesteF.CBU.M(m.ajuste,m.Sigma.P,p,G,m.C1,m.U,m.M)
  else{
    m.U[i] <- 1 
    m.U[i - 1] <- 0
    CBU <- rbind(CBU, TesteF.CBU.M(m.ajuste ,m.Sigma.P, p, G,
                                   m.C1, m.U, m.M))
  }
}
CBU <- (CBU %>% mutate(var = names(dados[,2:8])) )[,c(3,1,2)]
names(CBU) <- c("Variável","Estatística","p-valor")

print.xtable(xtable(CBU),include.rownames = F)

```

