---
title: "Saude_Mental"
author:
      - "Matheus Gomes"
      - "Daniela Moraes"
      - "Marcos Ferreira"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

```

#Saude

##Pacotes
```{r, message = F, warning = F}
source("funcoes.R")
source("ACaux.R")
pacotes <- c("magrittr",
             "xtable",
             "dplyr",
             "tidyr",
             "broom",
             "ca",
             "tables",
             "forcats",
             "tibble")

ipak(pacotes)
options(xtable.comment = FALSE,OutDec = ",")
```

##Lendo Os Dados

```{r}
dados <- read.table("Dados/Saudemental.txt")

nomesCOL <- c("A","B","C","D","E")
names(dados) <- c("A (Alto)","B","C","D","E (Baixo)")
saude <- c("Boa",
           "Presença fraca de sintomas",
           "Presença moderada de sintomas",
           "Debilitado")
rownames(dados) <- saude
##organizando
data <- dados %>% mutate(S = factor(saude))
data %<>% gather(Eco,Cont,-S)
dd <- data[rep(row.names(data), data$Cont), 1:2]
dd$S <- factor(dd$S) %>% fct_inorder()
tbl <- dd %$% ftable(S,Eco,dnn = c("Saúde mental","Status socioeconômico dos pais"))


```

##Praparação

```{r results="asis"}
xtableFtable(tbl)
```

##teste qui quadrado

$$p_{ij}=p_{i}\times p_{j} \qquad vs\qquad p_{ij}\ne p_{i}\times p_{j} \quad
\verb!para pelo menos um par(i,j)!$$

pi a proporção de observações na categoria i da variável “saúde mental”;

pj proporção de
observações na categoria j da variável “status socioeconômico dos pais”.


```{r results= "asis"}
qui_q <- tidy(chisq.test(dados))[c(1,3,2)] %>% as.data.frame() %>% 
   mutate_if(.predicate = is.numeric,funs(round(.,4)))
names(qui_q) <- c("Estatística Q","Graus de liberdade","p-valor")
qui_q$`Graus de liberdade` %<>% as.integer()

print(xtable(qui_q,digits = 3),include.rownames = F )
```

##proporção

```{r results="asis"}
prop <- dados/nrow(dd)*100
sum_row <- apply(prop,1,sum) %>% simplify2array()
sum_col <- apply(prop,2,sum) %>% simplify2array()
prop <- cbind(prop,sum_row) %>% 
rbind(sum_col)
names(prop)[6] <- "Total"
prop$Total[5] <- sum(prop$Total[1:4])
prop %<>%  mutate_if(.predicate = is.numeric,funs(round(.,2)))
row.names(prop) <- c(saude,"Total")


newrol <- rep(NA,6)
newcol <- rep(NA,6)
prop1 <- rbind(newrol,prop) 
prop1 <- cbind(newcol,prop1)
names(prop1)[1] <- "Status socioeconômico\n dos pais"
row.names(prop1)[1] <- "Saúde Mental"
print(xtable(prop1,align = "ll|lrcccc"),scalebox='0.85',
      hline.after = c(-1,1,nrow(prop1),nrow(prop1)-1))
```


##Perfis das linhas e perfis das colunas

```{r results="asis"}

resultaux <- ACaux(as.matrix(dados))
m.R<-100*resultaux$m.R %>% data.frame()
names(m.R)<- c("A (Alto)","B","C","D","E (Baixo)","Total")
row.names(m.R) <- c(saude,"Total")

newrol <- rep(NA,6)
newcol <- rep(NA,6)
prop1 <- rbind(newrol,m.R) 
prop1 <- cbind(newcol,prop1)
names(prop1)[1] <- "Status socioeconômico\n dos pais"
row.names(prop1)[1] <- "Saúde Mental"
print(xtable(prop1,align = "ll|lrcccc",caption = "perfil linhas",digits=2),scalebox='0.85',
      hline.after = c(-1,1,nrow(prop1),nrow(prop1)-1))


m.C<-100*resultaux$m.C %>% data.frame()
row.names(m.C)[5] <- "Total"
names(m.C)<-c("A (Alto)","B","C","D","E (Baixo)","Total")
newrol <- rep(NA,6)
newcol <- rep(NA,6)
prop1 <- rbind(newrol,m.C) 
prop1 <- cbind(newcol,prop1)
names(prop1)[1] <- "Status socioeconômico\n dos pais"
row.names(prop1)[1] <- "Saúde Mental"
print(xtable(prop1,align = "ll|lrcccc",caption = "perfil colunas",digits=2),scalebox='0.85',
      hline.after = c(-1,1,nrow(prop1),nrow(prop1)-1))

# xtable(100*m.R,digits=2,caption = "perfil linhas")
# xtable(100*m.C,digits=2,caption = "perfil colunas")

```



##Inercia

```{r results="asis",warning=F,message=F}

resultCA <- ca(dados)
inercia <- summary(resultCA)$scree
inercia_tbl <- cbind(sqrt(inercia[,2]), inercia[,2], inercia[,3], inercia[,4]) %>% data.frame()
inercia_tbl %<>%  mutate_if(.predicate = is.numeric,funs(round(.,4)))
names(inercia_tbl) <- c("Valor Singular","Inércia Princ.",
                        "Porcentual","Porcentual Acum.")
print(xtable(inercia_tbl,digits = c(1,3,3,2,2)), 
      include.rownames = F)
```

##componentes

```{r results="asis"}
resultFCA <- plot(resultCA,xlab="componente 1",ylab="componente 2",cex=1.2)
linhas <- resultFCA$rows %>% data.frame() 
colunas <- resultFCA$cols %>% data.frame() 
linhas <- tibble::rownames_to_column(linhas,"Categoria")
colunas <- tibble::rownames_to_column(colunas,"Categoria")

linhas %<>% mutate_if(.predicate = is.numeric,funs(round(.,2)))
colunas %<>% mutate_if(.predicate = is.numeric,funs(round(.,2)))
perfils <- bind_rows(linhas,colunas)
perfils$P <- c("Perfil Linhas",NA,NA,NA,"Perfil Colunas",NA,NA,NA,NA)
perfils <- perfils[,c(4,1:3)]
names(perfils) <- c("","Categoria","Componente 1","Componeste 2")

print(xtable(perfils),include.rownames = F, 
      hline.after = c(-1,0,nrow(perfils),4))
```


##biplot

```{r}
par(mfrow = c(1,1), mar = c(3, 0, 2, 0),cex=.9,cex.axis = 0.8,cex.lab = 1.1,mgp = c(1.5, .5, 0))
biplot(resultFCA$rows,resultFCA$cols,var.axes=FALSE,xlab="componente 1", ylab="componente 2",xlim=c(-.2,0.2))
abline(0,0,lty=2)
abline(v=0,lty=2)
```


